## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.admixture_plot.svg:Q: %.Q
	export POPINFO="$(find -L . -type f -name "*.txt")"
	echo "[DEBUG] Plotting admixture results for $prereq $POPINFO"
	Rscript --vanilla admixture_plotter.R $prereq $POPINFO $target
