## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.LD.maf_filtered.bed:Q: %.LD.converted.bed
	echo "[DEBUG] Filtering maf with plink  $prereq"
	$PLINK2 --bfile $stem.LD.converted \
	--maf $MAF \
	--make-bed \
	--threads $THREADS_PLINK \
	--out $stem.LD.maf_filtered \
	&& rm $stem.LD.converted.*

%.LD.converted.bed:Q: %.noLD.vcf
	echo "[DEBUG] Converting vcf to plink file $prereq"
	$PLINK2 --vcf $prereq \
	--keep-allele-order \
	--const-fid $FAM_ID \
	--vcf-filter \
	--vcf-half-call m \
	--vcf-require-gt \
	--make-bed \
	--threads $THREADS_PLINK \
	--out $stem.LD.converted
