## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.autosomal.popinfo.txt:Q: %.fam $TAG_FILE
	echo "[DEBUG] Exporting $TAG_FILE"
	Rscript --vanilla make_popinfo.R $prereq $target
