## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.autosomal.bed:Q: %.bed
	echo "[DEBUG] Keeping autosomal chromosomes from $prereq"
	$PLINK2 --bfile $stem \
	--chr 1-22 \
	--make-bed \
	--threads $THREADS_PLINK \
	--out $stem.autosomal
