## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.autosomal.log:Q: %.autosomal.bed
	echo "[DEBUG] Running admixture for $prereq"
	admixture --cv $prereq $K_VALUE > $stem.autosomal.K.$K_VALUE.log

%.autosomal.bed:Q: %.bed
	echo "[DEBUG] Keeping autosomal chromosomes"
	$PLINK --bfile $stem \
	--chr 1-22 \
	--make-bed \
	--threads $THREADS_PLINK \
	--out $stem.autosomal
