## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.admixture.log:Q: %.bed
	echo "[DEBUG] Running admixture for $prereq"
	echo "Gathering all admixture logs" > $target
	for kvalue in {2..9}
	do
		echo "[>..] runnning admixture for K=$kvalue"
		admixture \
			-j$ADMIXTURE_THREADS \
			--cv \
			--seed $SEED_VALUE \
			$prereq \
			$kvalue >> $target
	done
